# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: cpp
compiler: gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5
            - cmake
script:
    # Link gcc-5 and g++-5 to their standard commands
    - ln -s /usr/bin/gcc-5 /usr/local/bin/gcc
    - ln -s /usr/bin/g++-5 /usr/local/bin/g++
    # Export CC and CXX to tell cmake which compiler to use
    - export CC=/usr/bin/gcc-5
    - export CXX=/usr/bin/g++-5
    # Check versions of gcc, g++ and cmake
    - gcc -v && g++ -v && cmake --version

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libopencv-dev
    - pip install --user cpp-coveralls

install: export CXX="g++-5"

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./unit-tests

after_success:
    - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
    email: false
